feat: upgrade to Palm
overhangio/tutor-credentials pull request #2
Opened 2023-05-18 08:51 UTC by Faraz32123

v16.0.0

2023-05-22 07:12 UTC, regisb requested changes
Thanks for the PR! We'll need to upgrade the discovery plugin to deploy this on the Palm demo instance.

2023-05-22 07:12 UTC, regisb commented on tutorcredentials/templates/credentials/build/credentials/Dockerfile
> +ARG CREDENTIALS_VERSION={{OPENEDX_COMMON_VERSION}}
nit: `"{{ OPENEDX_COMMON_VERSION }}"`

2023-05-22 07:12 UTC, regisb commented on README.rst
> +    pip install git+https://github.com/overhangio/tutor-contrib-credentials.git
Can you please replace all instances of "contrib-credentials" by "credentials"? (including in setup.py)

2023-05-26 14:03 UTC, regisb requested changes
Looking good so far! @lpm0073 what do you think?

2023-05-26 14:03 UTC, regisb commented on .gitlab-ci.yml
> +    GITHUB_REPO: overhangio/tutor-credentials
Please add:

```
TUTOR_EXTRA_ENABLED_PLUGINS: discovery mfe
```

This is required to enable these extra plugins in CI.

2023-05-26 14:03 UTC, regisb commented on tutorcredentials/templates/credentials/build/credentials/Dockerfile
> +COPY {% if is_buildkit_enabled() %}--link {% endif %}--from=docker.io/powerman/dockerize:0.19.0 /usr/local/bin/dockerize /usr/local/bin/dockerize
Since Dockerize is not used at all anywhere in the plugin, I suggest that you remove all code related to Dockerize.

2023-05-26 14:08 UTC, lpm0073 commented
This looks GREAT! Thanks for including me in the review process. Looking forward to seeing this merged.

2023-05-26 14:10 UTC, lpm0073 commented
btw, i'm being presented with a "Merge pull request" action button, which i'm guess might not have been your intention. now that it's been formally adopted by overhangio @regisb would be the sole approver for merge requests, correct?

2023-05-26 14:15 UTC, regisb commented
Well Tutor has a maintainer program, where trusted committers can approve and push changes to the plugins: https://discuss.openedx.org/t/tutor-maintainers/7287 You certainly fall in that category :) Would you like to remain a maintainer or would you rather have a "hands-off" approach?

2023-05-26 14:28 UTC, lpm0073 commented
Good to know, and thank you again for including me. I'll be pleased to remain a maintainer on this as well as any future repos of mine that overhangio might adopt. 

For the merge I'll defer to your better judgement on this particular PR as i haven't sufficiently inspected the syntax and semantics of the code changes, though i'm happy to do that going forward :)

2023-05-30 07:22 UTC, Faraz32123 commented on README.rst
> +Credentials application supports course and program certificates. It offers an admin  panel where you can do configurations for your course and program.
I have changed it a little bit again, @regisb @lpm0073 let me know if its OK.
I have added a Note in it for expanding purpose. Should I keep it or remove it.

2023-06-14 22:30 UTC, merged